import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Experience from "@/components/Experience";
import Projects from "@/components/Projects";
import Skills from "@/components/Skills";
import BlogPreview from "@/components/BlogPreview";
import Footer from "@/components/Footer";
import Chatbot from "@/components/Chatbot";
